# Generated by Django 4.2.1 on 2023-08-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='previous_recommendations',
            field=models.TextField(blank=True),
        ),
    ]
